jobs:
  close-issues:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        close-issue-message: 'Closing due to lack of requested feedback. If you would
          like to proceed with your contribution, please provide the requested information
          and we will re-open this issue.

          '
        close-pr-message: 'Closing due to lack of requested feedback. If you would
          like to proceed with your contribution, please provide the requested information
          or make the requested changes, and we will re-open this pull request.

          '
        days-before-close: 21
        days-before-stale: 14
        only-labels: 'status: waiting-for-feedback'
        stale-issue-label: 'status: stale'
        stale-issue-message: 'If you would like us to be able to process this issue,
          please provide the requested information. If the information is not provided
          within the next 3 weeks, we will be unable to proceed and this issue will
          be closed.

          '
        stale-pr-label: 'status: stale'
        stale-pr-message: 'If you would like us to be able to process this pull request,
          please provide the requested information or make the requested changes.
          If the information is not provided or the requested changes are not made
          within the next 3 weeks, we will be unable to proceed and this pull request
          will be closed.

          '
name: Close inactive issues and PRs
on:
  repository_dispatch:
    types: trigger-ga___close-inactive-issues.yml
