jobs:
  combine-prs:
    if: github.repository == 'junit-team/junit5'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: combine-prs
      uses: github/combine-prs@v5.0.0
      with:
        github_token: ${{ secrets.GH_TOKEN }}
name: Combine PRs
on:
  repository_dispatch:
    types: trigger-ga___combine-prs.yml
