env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  JUNIT_DEVELOCITY_TESTDISTRIBUTION_ENABLED: true
jobs:
  openj9:
    name: OpenJ9 ${{ matrix.jdk }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - continue-on-error: true
      name: Set up Test JDK
      uses: ./.github/actions/setup-test-jdk
      with:
        distribution: semeru
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        check-latest: true
        distribution: semeru
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Prepare JDK${{ matrix.jdk }} env var
      run: echo "JDK${{ matrix.jdk }}=$JAVA_HOME" >> $GITHUB_ENV
      shell: bash
    - continue-on-error: true
      name: Build
      uses: ./.github/actions/run-gradle
      with:
        arguments: '-PjavaToolchain.version=${{ matrix.jdk }} \

          -PjavaToolchain.implementation=j9 \

          -Dscan.tag.JDK_${{ matrix.jdk }} \

          -Dscan.tag.OpenJ9 \

          build

          '
    strategy:
      fail-fast: false
      matrix:
        jdk:
        - 21
  openjdk:
    name: OpenJDK ${{ matrix.jdk }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - continue-on-error: true
      name: Set up Test JDK
      uses: ./.github/actions/setup-test-jdk
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk }}
      uses: oracle-actions/setup-java@v1
      with:
        release: ${{ matrix.jdk }}
        version: latest
        website: jdk.java.net
    - continue-on-error: true
      name: Prepare JDK${{ matrix.jdk }} env var
      run: echo "JDK${{ matrix.jdk }}=$JAVA_HOME" >> $GITHUB_ENV
      shell: bash
    - continue-on-error: true
      name: Build
      uses: ./.github/actions/run-gradle
      with:
        arguments: '-PjavaToolchain.version=${{ matrix.jdk }} \

          -Dscan.tag.JDK_${{ matrix.jdk }} \

          build

          '
    - continue-on-error: true
      name: Upload Test Distribution trace files
      uses: actions/upload-artifact@v4
      with:
        name: Test Distribution trace files (OpenJDK ${{ matrix.jdk }})
        path: '**/build/test-results/*/trace.json'
    strategy:
      fail-fast: false
      matrix:
        jdk:
        - 22
        - 23
        - 24
name: Cross-Version
on:
  repository_dispatch:
    types: trigger-ga___cross-version.yml
