jobs:
  dependency-submission:
    if: github.repository == 'junit-team/junit5'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        check-latest: true
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3
name: Gradle Dependency Submission
on:
  repository_dispatch:
    types: trigger-ga___gradle-dependency-submission.yml
permissions:
  contents: write
