jobs:
  label_issues:
    permissions:
      issues: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/github-script@v7
      with:
        script: "github.rest.issues.addLabels({\n  issue_number: context.issue.number,\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  labels: [\"\
          status: new\"]\n})\n"
name: Label new issues
on:
  repository_dispatch:
    types: trigger-ga___issue-labels.yml
