env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
jobs:
  check_build_reproducibility:
    name: Check build reproducibility
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - continue-on-error: true
      name: Restore Gradle cache and display toolchains
      uses: ./.github/actions/run-gradle
      with:
        arguments: --quiet
    - continue-on-error: true
      name: Build and compare checksums
      run: './gradle/scripts/checkBuildReproducibility.sh

        '
      shell: bash
name: Reproducible build
on:
  repository_dispatch:
    types: trigger-ga___reproducible-build.yml
